"""add_password_reset_columns

Revision ID: 77a34349ca1e
Revises: f6af221e91e6
Create Date: 2025-05-21 17:15:52.549031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a34349ca1e'
down_revision = 'f6af221e91e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('password_reset_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_reset_expires')
    op.drop_column('user', 'password_reset_token')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
